# SubChart values
redis:
  nameOverride: "redis-test"
  master:
    count: 1
    
    ##
    disableCommands:
      - FLUSHDB
      - FLUSHALL
    
    ##
    livenessProbe:
      enabled: true
      initialDelaySeconds: 40
      periodSeconds: 10
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 10
    
    ##
    readinessProbe:
      enabled: true
      initialDelaySeconds: 10
      periodSeconds: 2
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 10
    

    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi

  replica:
    replicaCount: 1
